import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { motion, AnimatePresence } from 'framer-motion';
import { Menu, X, Plane, MapPin, CalendarDays, Search, ShieldCheck, Headphones, Sparkles, BadgeDollarSign, ArrowRight, Star, ChevronDown, Mail, Phone, Clock3, Globe2, Send, Compass, Check, CheckCircle2, Users, ArrowUpRight } from 'lucide-react';
import './styles.css';

const destinations = [
  ['Santorini, Greece', 'From $640', 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80'],
  ['Kyoto, Japan', 'From $812', 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=900&q=80'],
  ['Amalfi, Italy', 'From $695', 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=900&q=80'],
  ['Marrakech, Morocco', 'From $574', 'https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=900&q=80']
];
const deals = [
  ['United Airlines', 'New York → London', '$498', 'UA'],
  ['Lufthansa', 'Chicago → Frankfurt', '$536', 'LH'],
  ['Emirates', 'Los Angeles → Dubai', '$722', 'EK']
];
const reviews = [
  ['“The whole experience felt considered, calm, and genuinely helpful. Our honeymoon route was effortless.”', 'Sofia M.', 'Chicago, IL'],
  ['“Clear options, great value, and a real person when I had a question. Exactly what travel planning should be.”', 'Daniel R.', 'Austin, TX'],
  ['“We found a brilliant fare for our family trip without the usual sea of confusing tabs.”', 'Aisha K.', 'New York, NY']
];
const faqs = [
  ['How does FaresFinders help me find flights?', 'We surface thoughtful flight ideas and clear fare options so you can compare with confidence. Search is visual in this demo and does not process bookings.'],
  ['Are the fares shown guaranteed?', 'Displayed prices are illustrative starting fares. Final availability and pricing always depend on the airline at time of booking.'],
  ['Can I get help choosing an itinerary?', 'Absolutely. Reach out to our travel team and we will help make the details feel simple.'],
  ['Do you charge a fee to search?', 'No. Exploring destinations and fare ideas is always free.']
];

function Logo(){ return <a className="logo" href="#home"><span><Plane size={19}/></span>Fares<span>Finders</span></a> }
function Nav({setPage}) { const [open,setOpen]=useState(false); const go=(p)=>{setPage(p);setOpen(false);window.scrollTo({top:0,behavior:'smooth'})}; return <header className="nav"><div className="nav-inner"><Logo/><nav className="desktop-nav"><button onClick={()=>go('home')}>Explore</button><button onClick={()=>go('about')}>Our story</button><button onClick={()=>go('contact')}>Contact</button></nav><button className="nav-cta desktop-only" onClick={()=>go('contact')}>Plan a trip <ArrowUpRight size={15}/></button><button className="menu" onClick={()=>setOpen(!open)} aria-label="Open menu">{open?<X/>:<Menu/>}</button></div><AnimatePresence>{open&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} className="mobile-nav"><button onClick={()=>go('home')}>Explore</button><button onClick={()=>go('about')}>Our story</button><button onClick={()=>go('contact')}>Contact</button></motion.div>}</AnimatePresence></header> }
function SearchCard(){ const [submitted,setSubmitted]=useState(false); const submit=(event)=>{event.preventDefault();setSubmitted(true)}; return <form className="search-card" onSubmit={submit}><div className="trip-tabs"><button type="button" className="active">Round trip</button><button type="button">One way</button><span className="travellers"><Users size={15}/> 1 traveller</span></div><div className="fields"><label><span>From</span><div><MapPin size={18}/><b>New York</b><small>JFK, United States</small></div></label><label><span>To</span><div><MapPin size={18}/><b>London</b><small>LHR, United Kingdom</small></div></label><label><span>When</span><div><CalendarDays size={18}/><b>Choose dates</b><small>Flexible dates</small></div></label><button type="submit" className="search-btn"><Search size={20}/><span>Find flights</span></button></div>{submitted&&<motion.div className="demo-results" initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} aria-live="polite"><div className="demo-results-heading"><span><CheckCircle2 size={17}/> Demo results for New York → London</span><small>Illustrative fares only</small></div><div className="demo-fares"><article><b>Atlantic Air</b><span>1 stop · 10h 25m</span><strong>$482</strong></article><article><b>Skyline Airways</b><span>Nonstop · 7h 05m</span><strong>$536</strong></article><article><b>Northstar</b><span>1 stop · 9h 40m</span><strong>$498</strong></article></div></motion.div>}</form> }
function Home({setPage}) { const [openFaq,setOpenFaq]=useState(0); return <>
 <main id="home"><section className="hero"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="container hero-grid"><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.65}}><div className="eyebrow"><Sparkles size={14}/> A more thoughtful way to fly</div><h1>Go further.<br/><i>Feel lighter.</i></h1><p className="hero-copy">Find your next escape with clear choices, lovely details, and fares worth getting excited about.</p><div className="hero-trust"><span><Check/> Clear, considered choices</span><span><Check/> Support when it matters</span></div></motion.div><motion.div className="hero-photo" initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{duration:.8,delay:.15}}><img src="https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1200&q=85" alt="Airplane above clouds"/><div className="photo-note"><span className="note-icon"><Plane size={18}/></span><div><b>Next stop: wonder</b><small>Thoughtful trips, beautifully simple</small></div></div></motion.div></div><div className="container search-wrap"><SearchCard/></div></section>
 <section className="section container"><div className="section-heading centered"><div className="eyebrow">Why FaresFinders</div><h2>The good kind of <i>travel planning.</i></h2><p>Made for people who want less noise and more of the world.</p></div><div className="features">{[[ShieldCheck,'Clear from the start','Simple fare ideas and no mystery language.'],[BadgeDollarSign,'Value you can feel','Smart options that make your budget go further.'],[Headphones,'Humanly helpful','Friendly support when your itinerary needs a second pair of eyes.'],[Sparkles,'Made for discovery','Fresh inspiration for your next brilliant escape.']].map(([Icon,title,text],i)=><motion.article className="feature-card" key={title} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.08}}><span className="feature-icon"><Icon/></span><h3>{title}</h3><p>{text}</p></motion.article>)}</div></section>
 <section className="section destination-section"><div className="container"><div className="section-heading split"><div><div className="eyebrow">Go somewhere beautiful</div><h2>Dream in <i>departure boards.</i></h2></div><a href="#deals" className="text-link">See all fare ideas <ArrowRight size={16}/></a></div><div className="destinations">{destinations.map(([place,price,img],i)=><motion.article className="destination" key={place} initial={{opacity:0,y:16}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><img src={img} alt={place}/><div><small>Return fares from</small><h3>{place}</h3><b>{price}</b><ArrowUpRight size={18}/></div></motion.article>)}</div></div></section>
 <section className="section container" id="deals"><div className="section-heading split"><div><div className="eyebrow">Curated fare ideas</div><h2>Airline deals,<br/><i>without the clutter.</i></h2></div><p className="side-copy">A few routes we’re watching for travelers ready to make a move.</p></div><div className="deal-grid">{deals.map(([airline,route,price,code],i)=><motion.article className="deal-card" key={airline} initial={{opacity:0,x:-15}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.08}}><span className={'airline-mark mark-'+i}>{code}</span><div><small>{airline}</small><h3>{route}</h3></div><div className="price"><small>Return from</small><b>{price}</b></div><button aria-label="View deal"><ArrowRight size={18}/></button></motion.article>)}</div><p className="fine-print">Fares shown are examples and may change based on availability. This website does not process bookings.</p></section>
 <section className="process"><div className="container process-grid"><div><div className="eyebrow light">Simple by design</div><h2>Less searching.<br/><i>More going.</i></h2><p>Three small steps between the first spark and a trip worth remembering.</p></div><div className="steps">{[['01','Share your spark','Tell us where your mind keeps wandering.'],['02','See the good options','Compare flight ideas that feel clear, not endless.'],['03','Choose your way forward','Move ahead with confidence and help close by.']].map(([n,t,x])=><div className="step" key={n}><b>{n}</b><div><h3>{t}</h3><p>{x}</p></div></div>)}</div></div></section>
 <section className="section container"><div className="section-heading centered"><div className="eyebrow">Traveller notes</div><h2>Loved by people who <i>like to go.</i></h2></div><div className="reviews">{reviews.map(([quote,name,city])=><article className="review" key={name}><div className="stars">{[1,2,3,4,5].map(x=><Star key={x} size={14} fill="currentColor"/>)}</div><p>{quote}</p><div className="reviewer"><span>{name[0]}</span><div><b>{name}</b><small>{city}</small></div></div></article>)}</div></section>
 <section className="section faq-section container"><div className="faq-title"><div className="eyebrow">A little clarity</div><h2>Questions,<br/><i>answered.</i></h2><p>Can’t see what you need? <button onClick={()=>setPage('contact')}>Talk to us.</button></p></div><div className="faq-list">{faqs.map(([q,a],i)=><article className={'faq '+(openFaq===i?'expanded':'')} key={q}><button onClick={()=>setOpenFaq(openFaq===i?-1:i)}>{q}<ChevronDown size={20}/></button><AnimatePresence>{openFaq===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{a}</motion.p>}</AnimatePresence></article>)}</div></section>
 <section className="container"><div className="cta"><div><div className="eyebrow light">Your next chapter is waiting</div><h2>Ready when<br/><i>you are.</i></h2><p>Start collecting the moments you’ll talk about for years.</p><button onClick={()=>setPage('contact')} className="cta-button">Start planning <ArrowRight size={17}/></button></div><img src="https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1000&q=85" alt="Mountain road at sunset"/></div></section>
 </main></> }
function StaticPage({type,setPage}){ const data={about:['Travel should feel like the beginning of something good.','FaresFinders LLC was created for curious people who value both the destination and the way they get there. We believe great travel starts with a clear mind, an open map, and someone in your corner.','We make the early stages of planning feel more human: less frantic comparison, more helpful perspective.'],contact:['Let’s plan a little magic.','Whether you have a route in mind or just a feeling you want to follow, we’d love to hear from you.','hello@faresfindersllc.com'],privacy:['Privacy, plainly put.','FaresFinders LLC respects your privacy. This static demonstration site does not create accounts, collect payment details, or operate a booking engine. If you contact us, we may use the details you provide solely to respond to your request.','We do not sell personal information. This policy may be updated as our services evolve.'],terms:['Terms & conditions.','This website is an informational showcase of FaresFinders LLC. Any fares, routes, availability, or travel details are illustrative and are not an offer, reservation, or guarantee.','Please confirm all travel details directly with the relevant providers before making decisions.']}; const [title,body,extra]=data[type]; return <main className="inner-page"><div className="container"><div className="eyebrow">FaresFinders LLC</div><h1>{title}</h1><div className="page-grid"><div><p>{body}</p><p>{extra}</p>{type==='contact'&&<div className="contact-details"><span><Mail/> hello@faresfindersllc.com</span><span><Phone/> +1 (800) 555-0148</span><span><Clock3/> Mon–Fri, 9am–6pm ET</span></div>}</div><aside><b>Looking for a new perspective?</b><p>Explore the world with a little more ease.</p><button onClick={()=>setPage('home')}>Back to exploring <ArrowRight size={16}/></button></aside></div></div></main> }
function Footer({setPage}){return <footer><div className="container footer-main"><div><Logo/><p>Better beginnings for every journey.</p><div className="social"><Globe2/><Send/><Compass/></div></div><div><b>Explore</b><button onClick={()=>setPage('home')}>Destinations</button><button onClick={()=>setPage('about')}>Our story</button><button onClick={()=>setPage('contact')}>Contact</button></div><div><b>Stay in the loop</b><p>Small notes on big horizons.</p><div className="email"><input placeholder="Your email address"/><button><ArrowRight size={17}/></button></div></div></div><div className="container footer-bottom"><span>© 2026 FaresFinders LLC. All rights reserved.</span><div><button onClick={()=>setPage('privacy')}>Privacy Policy</button><button onClick={()=>setPage('terms')}>Terms & Conditions</button></div></div></footer>}
function App(){ const [page,setPage]=useState('home'); return <><Nav setPage={setPage}/>{page==='home'?<Home setPage={setPage}/>:<StaticPage type={page} setPage={setPage}/>}<Footer setPage={setPage}/></> }
createRoot(document.getElementById('root')).render(<App/>);
